import type { Config } from "tailwindcss";

export default {
  content: [
    "./entrypoints/**/*.{html,tsx,ts}",
    "./components/**/*.{tsx,ts}",
    "./web/**/*.{tsx,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "ut-primary": "var(--ut-primary)",
        "ut-navy": "var(--ut-navy)",
        "ut-darkblue": "var(--ut-darkblue)",
        "ut-blue": "var(--ut-blue)",
        "ut-red": "var(--ut-red)",
        "ut-green": "var(--ut-green)",
        "ut-purple": "var(--ut-purple)",
        "ut-grey": "var(--ut-grey)",
        "ut-offwhite": "var(--ut-offwhite)",
        "ut-border": "var(--ut-border)",
        "ut-text": "var(--ut-text)",
        "ut-muted": "var(--ut-muted)",
        "ut-slate": "var(--ut-slate)",
        "ut-canvas": "var(--ut-canvas)",
        "ut-panel": "var(--ut-panel-bg)",
        "ut-white": "var(--ut-white)",
        tr: "var(--tr)",
        re: "var(--re)",
        uc: "var(--uc)",
        se: "var(--se)",
        tc: "var(--tc)",
        "score-0": "var(--score-0)",
        "score-1": "var(--score-1)",
        "score-1-strong": "var(--score-1-strong)",
        "score-2": "var(--score-2)",
        "score-3": "var(--score-3)",
        "state-warning": "var(--state-warning)",
        "state-error-border": "var(--state-error-border)",
        "state-success-border": "var(--state-success-border)",
        "state-warning-border": "var(--state-warning-border)",
        "badge-pass-tint": "var(--badge-pass-tint)",
        "badge-magenta-tint": "var(--badge-magenta-tint)",
        "trust-magenta": "var(--trust-magenta)",
        "trust-magenta-strong": "var(--trust-magenta-strong)",
        "trust-magenta-tint": "var(--trust-magenta-tint)",
        "trust-magenta-border": "var(--trust-magenta-border)",
        "lisa-red": "var(--lisa-red)",
        "eis-teal": "var(--eis-teal)",
      },
      fontFamily: {
        body: ["var(--ff-body)"],
        heading: ["var(--ff-heading)"],
        mono: ["var(--ff-mono)"],
        display: ["var(--ff-display)"],
      },
      fontSize: {
        "ut-xs": "var(--text-xs)",
        "ut-sm": "var(--text-sm)",
        "ut-md": "var(--text-md)",
        "ut-body": "var(--text-body)",
        "ut-sub": "var(--text-sub)",
        "ut-hero": "var(--text-hero)",
        "ut-badge": "var(--text-badge)",
        "ut-2xs": "var(--text-2xs)",
        "ut-heading": "var(--text-heading)",
      },
      borderRadius: {
        none: "0px",
        "ut-sm": "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        "ut-lg": "var(--radius-lg)",
      },
      borderWidth: {
        accent: "6px",
      },
      spacing: {
        "ut-1": "var(--space-1)",
        "ut-2": "var(--space-2)",
        "ut-3": "var(--space-3)",
        "ut-4": "var(--space-4)",
        "ut-5": "var(--space-5)",
        "ut-6": "var(--space-6)",
        "ut-8": "var(--space-8)",
      },
      letterSpacing: {
        "ut-heading": "var(--ls-heading)",
        "ut-label": "var(--ls-label)",
        "ut-uppercase": "var(--ls-uppercase)",
        "ut-kicker": "var(--ls-kicker)",
        "ut-panel-title": "var(--ls-panel-title)",
      },
      animation: {
        "pulse-capture": "pulse-capture 1s ease-in-out infinite",
      },
      keyframes: {
        "pulse-capture": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
