export const DATA_SOURCE_OPTIONS = [
  "CrossRef",
  "OpenAlex",
  "OpenCitations",
  "DataCite",
  "Scopus",
  "Web of Science",
  "PubMed",
  "Semantic Scholar",
  "Google Scholar",
  "IEEE Xplore",
  "JSTOR",
  "arXiv",
  "bioRxiv",
  "MedRxiv",
  "ERIC",
  "PsycINFO",
  "ProQuest",
  "Dimensions",
  "BASE",
  "CORE",
  "Cochrane Library",
  "ACM Digital Library",
] as const;

export const SEARCH_METHOD_OPTIONS = [
  "Keywords",
  "Semantic search",
  "Boolean queries",
  "Natural language",
  "Citation chaining",
  "Faceted filtering",
  "Vector search",
  "Hybrid search",
  "Controlled vocabulary / MeSH",
] as const;

export const DISCIPLINE_OPTIONS = [
  "Agricultural and Biological Sciences",
  "History and Archaeology",
  "Languages and Literature",
  "Philosophy and Ethics",
  "Performing Arts",
  "Visual Arts and Design",
  "Religious Studies",
  "Biochemistry, Genetics and Molecular Biology",
  "Business, Management and Accounting",
  "Chemical Engineering",
  "Chemistry",
  "Computer Science",
  "Decision Sciences",
  "Dentistry",
  "Earth and Planetary Sciences",
  "Economics, Econometrics and Finance",
  "Energy",
  "Engineering",
  "Environmental Science",
  "Health Professions",
  "Immunology and Microbiology",
  "Materials Science",
  "Mathematics",
  "Medicine",
  "Neuroscience",
  "Nursing",
  "Pharmacology, Toxicology and Pharmaceutics",
  "Physics and Astronomy",
  "Psychology",
  "Education and Educational Research",
  "Law, Policy, and Criminology",
  "Political Science and International Relations",
  "Sociology, Anthropology, and Social Work",
  "Veterinary",
  "Multidisciplinary",
  "Information Science and Library Science",
  "Communication and Media Studies",
  "Geography",
] as const;

export const AUTH_METHOD_OPTIONS = [
  "SSO/SAML",
  "IP Authentication",
  "OpenAthens",
  "Proxy (EZproxy)",
  "LibKey",
  "Email-only",
  "API Key",
  "None required",
  "Personal account",
] as const;

export const DISCIPLINE_DEFAULT = "Multidisciplinary";
export const DISCIPLINE_OTHERS = DISCIPLINE_OPTIONS.filter((d) => d !== DISCIPLINE_DEFAULT);
export const MAX_CUSTOM_LENGTH = 120;
