import { bench, describe } from "vitest";
import { minifyCss, minifyHtml, sanitizeFilename } from "@/lib/export";

// ── HTML samples ──────────────────────────────────────────────────────

const SAMPLE_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TRUST Evaluation Report</title>
  <link rel="stylesheet" href="report.css">
</head>
<body>
  <header>
    <h1>TRUST Evaluation Report</h1>
    <p>Generated on 2025-01-15 14:30</p>
  </header>
  <main>
    <section class="nutrition-label">
      <div class="principle-row">
        <span class="principle-name">Transparent</span>
        <span class="circles">
          <span class="circle filled">&#9679;</span>
          <span class="circle filled">&#9679;</span>
          <span class="circle filled">&#9679;</span>
          <span class="circle empty">&#9675;</span>
        </span>
      </div>
      <div class="principle-row">
        <span class="principle-name">Reliable</span>
        <span class="circles">
          <span class="circle filled">&#9679;</span>
          <span class="circle filled">&#9679;</span>
          <span class="circle empty">&#9675;</span>
          <span class="circle empty">&#9675;</span>
        </span>
      </div>
    </section>
    <section class="category-details">
      <h2>Transparent (TR)</h2>
      <div class="question-row">
        <p class="question-text">Does the tool clearly state what data sources it uses?</p>
        <p class="evidence">Evidence: The tool's about page lists PubMed, Semantic Scholar, and arXiv.</p>
      </div>
    </section>
  </main>
  <!-- Footer with metadata -->
  <footer>
    <p class="muted">Report generated by TRUST Review Extension</p>
  </footer>
</body>
</html>`;

const LARGE_HTML = SAMPLE_HTML.repeat(20);

// ── CSS samples ──────────────────────────────────────────────────────

const SAMPLE_CSS = `
/* TRUST Report Styles */
:root {
  --magenta: #8e036c;
  --muted: #6c757d;
  --text: #212529;
  --ff-heading: "Inter", sans-serif;
  --spacing: 16px;
  --radius: 8px;
  --bg: #f8f9fa;
  --border: #dee2e6;
}

body {
  font-family: system-ui, -apple-system, sans-serif;
  color: var(--text);
  background: #fff;
  max-width: 800px;
  margin: 0 auto;
  padding: var(--spacing);
}

h1 {
  color: var(--magenta);
  font-family: var(--ff-heading);
  margin-bottom: var(--spacing);
}

.card {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: var(--spacing);
  color: var(--text);
}

.muted {
  color: var(--muted);
  font-size: 0.875rem;
}

.dist-bar {
  display: flex;
  height: 10px;
  border-radius: 2px;
  overflow: hidden;
}

.dist-seg {
  height: 100%;
}

// Line comment
.footer {
  margin-top: var(--spacing);
  color: var(--muted);
}
`;

const LARGE_CSS = SAMPLE_CSS.repeat(10);

// ── sanitizeFilename inputs ──────────────────────────────────────────

const FILENAME_INPUTS = {
  simple: "MyReport",
  specialChars: 'Test<Tool>:"Report"/file\\name|?.doc',
  pathTraversal: "../../etc/passwd",
  controlChars: "file\x00name\x1Fwith\x0Acontrol",
  longMixed:
    'A Very Long Tool Name With Special <Characters> & "Quotes" / Slashes \\ And More | Symbols ? * End',
  unicode: "Ünïcödé Tööl Nâmé — with «dashes»",
  multipleDots: "...hidden..file...txt",
  whitespace: "  tool name with spaces  ",
  empty: "",
};

// ── Benchmarks ────────────────────────────────────────────────────────

describe("sanitizeFilename", () => {
  bench("simple ASCII name", () => {
    sanitizeFilename(FILENAME_INPUTS.simple);
  });

  bench("special characters", () => {
    sanitizeFilename(FILENAME_INPUTS.specialChars);
  });

  bench("path traversal attempt", () => {
    sanitizeFilename(FILENAME_INPUTS.pathTraversal);
  });

  bench("control characters", () => {
    sanitizeFilename(FILENAME_INPUTS.controlChars);
  });

  bench("long mixed content", () => {
    sanitizeFilename(FILENAME_INPUTS.longMixed);
  });

  bench("unicode characters", () => {
    sanitizeFilename(FILENAME_INPUTS.unicode);
  });

  bench("multiple dots", () => {
    sanitizeFilename(FILENAME_INPUTS.multipleDots);
  });

  bench("whitespace padding", () => {
    sanitizeFilename(FILENAME_INPUTS.whitespace);
  });

  bench("empty string fallback", () => {
    sanitizeFilename(FILENAME_INPUTS.empty);
  });
});

describe("minifyHtml", () => {
  bench("small report document", () => {
    minifyHtml(SAMPLE_HTML);
  });

  bench("large report document (20x)", () => {
    minifyHtml(LARGE_HTML);
  });
});

describe("minifyCss", () => {
  bench("report stylesheet with variables", () => {
    minifyCss(SAMPLE_CSS);
  });

  bench("large stylesheet (10x)", () => {
    minifyCss(LARGE_CSS);
  });
});
