import { AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig } from "remotion";
import { buildNutritionLabel, REPORT_CSS } from "@/lib/html-report";
import { RUBRIC_DATA } from "@/data/rubrics";
import type { Evaluation, ReviewFinalization, SessionMetadata } from "@/lib/types";
import { useEffect, useState } from "react";

const DEMO_METADATA: SessionMetadata = {
  id: "demo",
  toolName: "Consensus",
  toolUrl: "https://consensus.app",
  startTime: new Date().toISOString(),
  rubricId: "trust-full",
  usesAi: true,
  status: "active",
  description: "AI-powered research assistant",
  dataSources: ["Academic papers (Semantic Scholar)"],
  company: "Consensus Inc.",
};

const DEMO_EVALUATIONS: Evaluation[] = [
  { rubricId: "TR.data_source_clarity", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "TR.methodology_transparency", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "RE.accuracy_and_hallucination", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "RE.error_correction", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "US.interface_clarity", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "US.response_quality", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "SE.scope_clarity", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "SE.evidence_quality", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "TC.provenance_tracking", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "TC.citation_integrity", score: 2, notes: "", explicitEvidenceIds: [] },
];

const DEMO_FINALIZATION: ReviewFinalization = {
  finalizedAt: new Date().toISOString(),
  grade: "pass",
  conclusion:
    "Consensus demonstrates strong transparency and usability. Clear source attribution and intuitive interface.",
  strengths: ["Clear source attribution", "Intuitive search interface", "Good academic coverage"],
  weaknesses: ["Limited methodology disclosure", "Data provenance could be more transparent"],
};

/**
 * TrustExplainer: Animated reveal of the TRUST nutrition label.
 * Shows the real report card generated by the extension's actual code.
 *
 * Timeline (10s @ 30fps = 300 frames):
 *   0-45:   Title "TRUST" fades in
 *   45-75:  Tagline fades in
 *   75-120: Label card scales in (spring)
 *   120-240: Full label visible, steady
 *   240-300: Fade to closing text
 */
export function TrustExplainer() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const [labelHtml, setLabelHtml] = useState("");

  useEffect(() => {
    buildNutritionLabel(DEMO_METADATA, DEMO_EVALUATIONS, RUBRIC_DATA, DEMO_FINALIZATION).then(
      (html) => {
        // Extract just the <main> content (strip outer html/head/body)
        const mainMatch = html.match(/<main[^>]*>([\s\S]*)<\/main>/);
        setLabelHtml(mainMatch?.[1] ?? html);
      },
    );
  }, []);

  // Phase 1: Title (frames 0-45)
  const titleOpacity = interpolate(frame, [0, 30, 45], [0, 1, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const showTitle = frame < 120;

  // Phase 2: Tagline (frames 45-75)
  const taglineOpacity = interpolate(frame, [45, 65, 75], [0, 1, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Phase 3: Label card (frames 75+)
  const labelSpring = spring({
    frame: Math.max(0, frame - 75),
    fps,
    config: { damping: 18, stiffness: 80 },
  });
  const labelScale = interpolate(labelSpring, [0, 1], [0.8, 1]);
  const labelOpacity = interpolate(frame, [75, 100], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Phase 4: Closing text (frames 240-300)
  const closingOpacity = interpolate(frame, [240, 270, 290, 300], [0, 1, 1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const showClosing = frame >= 240;

  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#f8f9fa",
        fontFamily: "var(--ff-body, system-ui, sans-serif)",
      }}
    >
      {/* Title overlay */}
      {showTitle && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 10,
          }}
        >
          <div
            style={{
              opacity: titleOpacity,
              fontSize: 72,
              fontWeight: 900,
              fontFamily: "var(--ff-display, system-ui)",
              color: "var(--trust-magenta, #a83279)",
              letterSpacing: "0.15em",
            }}
          >
            TRUST
          </div>
          <div
            style={{
              opacity: taglineOpacity,
              fontSize: 18,
              color: "#666",
              marginTop: 8,
              letterSpacing: "0.05em",
            }}
          >
            Information Tool Reviews
          </div>
        </div>
      )}

      {/* Nutrition label */}
      {labelHtml && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            opacity: labelOpacity,
            transform: `scale(${labelScale})`,
            padding: 40,
          }}
        >
          <div
            style={{
              maxWidth: 520,
              width: "100%",
              boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
              borderRadius: 8,
              overflow: "hidden",
              background: "white",
            }}
          >
            <style>{REPORT_CSS}</style>
            {/* biome-ignore lint/security/noDangerouslySetInnerHtml: labelHtml is generated by our own buildNutritionLabel with esc() sanitization */}
            <div dangerouslySetInnerHTML={{ __html: labelHtml }} />
          </div>
        </div>
      )}

      {/* Closing overlay */}
      {showClosing && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            background: "rgba(248,249,250,0.92)",
            zIndex: 20,
            opacity: closingOpacity,
          }}
        >
          <div style={{ fontSize: 20, color: "#444", textAlign: "center" }}>
            <span style={{ fontWeight: 700, color: "var(--trust-magenta, #a83279)" }}>
              5 principles
            </span>{" "}
            ·{" "}
            <span style={{ fontWeight: 700, color: "var(--trust-magenta, #a83279)" }}>
              10 questions
            </span>{" "}
            ·{" "}
            <span style={{ fontWeight: 700, color: "var(--trust-magenta, #a83279)" }}>
              1 verdict
            </span>
          </div>
        </div>
      )}
    </AbsoluteFill>
  );
}
