import { AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig } from "remotion";
import { buildNutritionLabel, REPORT_CSS } from "@/lib/html-report";
import { RUBRIC_DATA } from "@/data/rubrics";
import type { Evaluation, ReviewFinalization, SessionMetadata } from "@/lib/types";
import { useEffect, useState } from "react";

const DEMO_METADATA: SessionMetadata = {
  id: "demo",
  toolName: "Consensus",
  toolUrl: "https://consensus.app",
  startTime: new Date().toISOString(),
  rubricId: "trust-full",
  usesAi: true,
  status: "active",
  description: "AI-powered research assistant",
  dataSources: ["Academic papers (Semantic Scholar)"],
  company: "Consensus Inc.",
};

const DEMO_EVALUATIONS: Evaluation[] = [
  { rubricId: "TR.data_source_clarity", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "TR.methodology_transparency", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "RE.accuracy_and_hallucination", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "RE.error_correction", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "US.interface_clarity", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "US.response_quality", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "SE.scope_clarity", score: 3, notes: "", explicitEvidenceIds: [] },
  { rubricId: "SE.evidence_quality", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "TC.provenance_tracking", score: 2, notes: "", explicitEvidenceIds: [] },
  { rubricId: "TC.citation_integrity", score: 2, notes: "", explicitEvidenceIds: [] },
];

const DEMO_FINALIZATION: ReviewFinalization = {
  finalizedAt: new Date().toISOString(),
  grade: "pass",
  conclusion:
    "Consensus demonstrates strong transparency and usability. Clear source attribution and intuitive interface.",
  strengths: ["Clear source attribution", "Intuitive search interface", "Good academic coverage"],
  weaknesses: ["Limited methodology disclosure", "Data provenance could be more transparent"],
};

/**
 * TrustExplainer: Animated reveal of the TRUST nutrition label.
 * Shows the real report card generated by the extension's actual code.
 *
 * Timeline (10s @ 30fps = 300 frames):
 *   0-60:   Title "TRUST" + subtitles fade in
 *   60-100: Title crossfades out, label slides up and fades in (spring)
 *   100-240: Label fully visible, steady
 *   240-285: Label fades, closing text appears
 *   285-300: Everything fades out
 */
export function TrustExplainer() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const [labelHtml, setLabelHtml] = useState("");

  useEffect(() => {
    buildNutritionLabel(DEMO_METADATA, DEMO_EVALUATIONS, RUBRIC_DATA, DEMO_FINALIZATION).then(
      (html) => {
        // Extract just the <main> content (strip outer html/head/body)
        const mainMatch = html.match(/<main[^>]*>([\s\S]*)<\/main>/);
        setLabelHtml(mainMatch?.[1] ?? html);
      },
    );
  }, []);

  // ── Phase 1: Title (frames 0-60) ──────────────────────────────────────
  const titleOpacity = interpolate(frame, [0, 30], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const subtitleOpacity = interpolate(frame, [20, 40], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const tertiaryOpacity = interpolate(frame, [35, 50], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  // Title fades out during crossfade (60→80)
  const titleFadeOut = interpolate(frame, [60, 80], [1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // ── Phase 2: Label reveal (frames 60-100) ─────────────────────────────
  const labelSpring = spring({
    frame: Math.max(0, frame - 70),
    fps,
    config: { damping: 20, stiffness: 70 },
  });
  const labelY = interpolate(labelSpring, [0, 1], [20, 0]);
  const labelOpacity = interpolate(frame, [70, 100], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Background transitions from black to #f8f9fa during crossfade
  const bgFade = interpolate(frame, [60, 90], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // ── Phase 4: Closing (frames 240-300) ─────────────────────────────────
  const closingWhiteOverlay = interpolate(frame, [240, 275], [0, 0.9], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const closingTextOpacity = interpolate(frame, [250, 270], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  // Label fades to 50% during closing
  const labelClosingFade = interpolate(frame, [240, 275], [1, 0.5], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  // Final fade-out (285-300)
  const finalFadeOut = interpolate(frame, [285, 300], [1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Computed label opacity combines reveal + closing phases
  const computedLabelOpacity =
    frame < 240 ? labelOpacity : labelClosingFade * finalFadeOut;

  // Computed closing overlay opacity includes final fade-out
  const computedClosingOpacity =
    frame < 240 ? 0 : closingTextOpacity * finalFadeOut;

  // Computed bg: interpolate rgb from black to #f8f9fa
  const bgR = Math.round(interpolate(bgFade, [0, 1], [0, 248]));
  const bgG = Math.round(interpolate(bgFade, [0, 1], [0, 249]));
  const bgB = Math.round(interpolate(bgFade, [0, 1], [0, 250]));

  return (
    <AbsoluteFill
      style={{
        backgroundColor: `rgb(${bgR},${bgG},${bgB})`,
        fontFamily: "system-ui, sans-serif",
      }}
    >
      {/* Phase 1: Title overlay */}
      {frame < 80 && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 10,
            opacity: titleFadeOut,
          }}
        >
          <div
            style={{
              opacity: titleOpacity,
              fontSize: 80,
              fontWeight: 900,
              fontFamily: "system-ui",
              color: "#8e036c",
              letterSpacing: "0.15em",
            }}
          >
            TRUST
          </div>
          <div
            style={{
              opacity: subtitleOpacity,
              fontSize: 20,
              color: "#999",
              fontFamily: "system-ui",
              marginTop: 12,
            }}
          >
            A framework for reviewing AI tools
          </div>
          <div
            style={{
              opacity: tertiaryOpacity,
              fontSize: 14,
              color: "#777",
              fontFamily: "system-ui",
              marginTop: 8,
            }}
          >
            Information Evaluation Label
          </div>
        </div>
      )}

      {/* Phase 2/3: Nutrition label card */}
      {labelHtml && frame >= 70 && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            opacity: computedLabelOpacity,
            transform: `translateY(${labelY}px)`,
            padding: 40,
            zIndex: 5,
          }}
        >
          <div
            style={{
              maxWidth: 480,
              width: "100%",
              boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
              borderRadius: 0,
              overflow: "hidden",
              background: "white",
            }}
          >
            <style>{REPORT_CSS}</style>
            {/* biome-ignore lint/security/noDangerouslySetInnerHtml: labelHtml is generated by our own buildNutritionLabel with esc() sanitization */}
            <div dangerouslySetInnerHTML={{ __html: labelHtml }} />
          </div>
        </div>
      )}

      {/* Phase 4: Closing overlay */}
      {frame >= 240 && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 20,
            background: `rgba(255,255,255,${closingWhiteOverlay * finalFadeOut})`,
            opacity: computedClosingOpacity,
          }}
        >
          <div style={{ fontSize: 24, color: "#333", textAlign: "center" }}>
            <span style={{ color: "#8e036c", fontWeight: 700 }}>5</span>{" "}
            principles ·{" "}
            <span style={{ color: "#8e036c", fontWeight: 700 }}>10</span>{" "}
            questions ·{" "}
            <span style={{ color: "#8e036c", fontWeight: 700 }}>1</span>{" "}
            verdict
          </div>
        </div>
      )}
    </AbsoluteFill>
  );
}
